runtime: python
env: flex

entrypoint: gunicorn -b :$PORT app:app  # Assuming your Flask app is in main.py

instance_class: F1  # or a larger instance depending on your needs

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GEMINI_API_KEY: "AIzaSyApPJgKHOZIk9UfkjwYq9Lpk64tq5oyGvQ"
  OLA_MAPS_API_KEY: "rxS3WOVB7zNbC0kvfLtpljJVa6lAqoIZpoqsytwU"
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
  GOOGLE_CLOUD_PROJECT: "trackbeez"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

